### ISSUE TITLE
Add initial tab to header line of matrix table output

### ISSUE THREAD

**Issue by mvences** [iTaxoTools/TaxI2#29]
The output of TaxI3 includes a series of matrix-like tables, mostly presenting distances between pairs of species or genera. The tables are printed as tab-delimited text, which allows copy-pasting them into a spreadsheet editor such as Excel. However, a minor problem is that the header line lacks one initial tabulator, so that it is shifted to the left when copying it into Excel (first example in the screenshot below). Instead, the header line should start with a tabulator line so that the result in Excel will look like the second example in the following screenshot.

![image](https://user-images.githubusercontent.com/66744055/131231763-e9171d66-ad15-4a4d-82a1-62f1e8119406.png)

When working on this issue, maybe also check the output of morphometricanalyzer and dnadiagnoser where I think there are also matrix tables produced, and make sure an initial tab is also added for the output of those programs.

**Comment by necrosovereign** [comment]
It seems that morphometricanalyzer and dnadiagnoser are not affected by this issue
